
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/sporting-grotesque/SportingGrotesque-Regular.otf",
      weight: "400",
    },
    {
      path: "../public/fonts/sporting-grotesque/SportingGrotesque-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-myfont",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} antialiased  `}>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
